### ISSUE TITLE
Can I use this library for network communication

### ISSUE THREAD

**Issue by saatsazov** [zachsaw/Binaron.Serializer#50]
Hello,

I have a problem with generic de serialization. I tried to use code from the readme, but it seems not working.

```cs
var input = new Employee
{
	FirstName = "Hello",
	LastName = "Worlds",
	BirthDate = DateTime.UtcNow,
};

using (var stream = new MemoryStream())
{
	BinaronConvert.Serialize(input, stream, new SerializerOptions
	{
		SkipNullValues = true,
		CustomObjectIdentifierProviders = { new PersonIdentifierProvider() }
	});
	stream.Position = 0;
	// this cause an exception.
	var person = BinaronConvert.Deserialize<IPerson>(stream, new DeserializerOptions
	{
		CustomObjectFactories = { new PersonFactory() }
	});

	stream.Position = 0;
}
```

I made a simple project you can see whole source code https://github.com/saatsazov/binaron-test/blob/master/UnitTest1.cs#L70

Test `TestMethod3` is failing with this error
```
Exception has occurred: CLR/System.TypeInitializationException
An exception of type 'System.TypeInitializationException' occurred in Binaron.Serializer.dll but was not handled in user code: 'The type initializer for 'GetObjectReaderGeneric`1' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.NotSupportedException : Interface 'tests.UnitTest1+IPerson' is not supported
   at Binaron.Serializer.Accessors.SetterHandler.GetActualType(Type type)
   at Binaron.Serializer.Accessors.SetterHandler.CreateActivatorsAndSetters(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Binaron.Serializer.Accessors.SetterHandler.GetActivatorAndSetterHandlers(Type type)
   at Binaron.Serializer.TypedDeserializer.ObjectReaders.CreateReader(Type type)
   at Binaron.Serializer.TypedDeserializer.ObjectReaders.CreateReader[T]()
   at Binaron.Serializer.TypedDeserializer.GetObjectReaderGeneric`1..cctor()
   ```

What I want to achieve is client-server communication via messages. So as I assume messages somehow isolated in stream? By implementing CustomObjectIdentifierProvider we kinda specify message id which should be unique in our protocol. I'm I right?

**Comment by saatsazov** [comment]
I'm currently using https://github.com/chronoxor/FastBinaryEncoding which was make sense when we have client and server on different languages. Now everything is c# so I'm trying to write models in c# instead of specific language.
